trigger:
  branches:
    include:
    - master
    
jobs:
  - job: 'Test1'
    pool:
      name: 'default'
    strategy:
      parallel: 4  
    steps:
      - checkout: self
        clean: false
        fetchDepth: 2
      - script: octave --no-gui --eval "disp(pwd); ls; bootstrapTestAzure; cd('Test/MoxUnitCompatible/quickMoxTests'); res=moxunit_runtests('-recursive'); exit(~res);"
        displayName: QuickMox
      - script: octave --no-gui --eval "disp(pwd); ls; bootstrapTestAzure; cd('Test/MoxUnitCompatible'); res=moxunit_runtests('BatchExample_qmt_sirfse_test.m'); exit(~res);"
        displayName: qmt_sirfse
      
