# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  name: 'default'

variables:
  imageName: 'neuropoly/qmrlab2:$(build.buildId)'

trigger:
  branches:
    include:
    - master
    - tristano_azure
    
steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: false
  fetchDepth: 2
- script: octave --no-gui --eval "bootstrapTestAzure;cd('Test/MoxUnitCompatible/quickMoxTests'); \
          res=moxunit_runtests('-recursive'); \
          exit(~res);" 

